name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.8
#          arguments: build
#          build-root-directory: app
      - name: Build project and run tests
        id: test
        run: ./gradlew build jacocoTestReport
      - name: Download CC Reporter
        run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-reporter
      - name: Make CC Reporter executable
        run: chmod +x ./cc-reporter
      - name: Run CC Reporter before-build
        run: ./cc-reporter before-build
      - name: Upload coverage to CodeClimate
        run: ./cc-reporter after-build --exit-code ${{ steps.tests.outcome }} --id ${{ secrets.CC_TEST_REPORTER_ID }}
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: app/src/main/java
        with:
          coverageCommand: make -C app report
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco

